
/*
This file is generated by PI_windll_from_lib plugin for GnumakeUniproc. Do not modify it manually.
*/
void _ExportFunctionList(void)
{
	/* Auto-export functions from GMU project(gmu_PRJ_NAME): gadgetlib
	*/
	{
	extern void gadgetlib__gadgetlib__DLL_AUTO_EXPORT_STUB(void);
	gadgetlib__gadgetlib__DLL_AUTO_EXPORT_STUB();
	}
}
