#### template file for use with pattern-container1.mks, [GnumakeUniproc v1.0]
# ! Be sure to replace every occurrence of <angle-brackets> to be your
# actual content, or [ at least comment them out if some of them are
# not required] .

gmu_PRJ_NAME = mmsnprintf.sdk


gmp_u_list_PLUGIN_TO_LOAD += PI_makesdk_2011
gmi_MSDK1_up_BUILDSDK_INI = buildsdk.ini


gmp_u_list_PLUGIN_TO_LOAD += PI_sc_pdb_sew_svn
  gmi_SCPSS_ud_PDB = $(gmb_syncto)
  gmi_SCPSS_ud_source = ../..
  gmi_SCPSS_PRODUCT_NAME = mm_snprintf
  gmi_SCPSS_PRODUCT_VER = 4.2# optional?
  gmi_SCPSS_SYMSTORE_TARGET_DIR = $(CURDIR)/WebSymbols
  gmu_up_list_STARTUP_CLEAR_FILES += $(gmi_SCPSS_SYMSTORE_TARGET_DIR)/index2.txt
	# Create index2.txt to have a three-tier directory structure.
  gmi_SCPSS_SVNHOST_TABLE = # use default
  gmi_SCPSS_list_REPOSIE_TABLE_SVNURL = # use default

gmp_USER_POST_TARGETS += gmit_SCPSS_SEW_PDB


include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1-container.mks

