
/*
This file is generated by PI_dll_from_lib plugin for GnumakeUniproc. Do not modify it manually.
*/
void _ExportFunctionList(void)
{
	/* Auto-export functions from GMU project(gmu_PRJ_NAME): gadgetlib.lib
	*/
	{
	extern void gadgetlib_lib__fstream_aux__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__T_string_glibc__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib__gadgetlib__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__time_common__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__charenccvt_common__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__gsm0338cvt__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__mbcs_ops__DLL_AUTO_EXPORT_STUB(void);
	extern void gadgetlib_lib__T_string__DLL_AUTO_EXPORT_STUB(void);
	gadgetlib_lib__fstream_aux__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__T_string_glibc__DLL_AUTO_EXPORT_STUB();
	gadgetlib__gadgetlib__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__time_common__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__charenccvt_common__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__gsm0338cvt__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__mbcs_ops__DLL_AUTO_EXPORT_STUB();
	gadgetlib_lib__T_string__DLL_AUTO_EXPORT_STUB();
	}
}
