MMSNPRINTF_NO_UNICODE = 1

gmp_PS_INCLUDE_SUBDIRS = armcpp

gmu_up_list_SRC_FROM_ROOT += glibc/mm_psfunc.cpp
	# Yes, use the same mm_psfunc.cpp as glibc, currently.

gmu_ud_list_PRJ_HEADER += $(gmu_ud_SRC_ROOT)/armcpp

include ../lib-all-compiler.mki