
/*
This file is generated by PI_dll_from_lib plugin for GnumakeUniproc. Do not modify it manually.
*/
void _ExportFunctionList(void)
{
	/* Auto-export functions from GMU project(gmu_PRJ_NAME): sgetopt.lib
	*/
	{
	extern void sgetopt_lib__sgetopt__DLL_AUTO_EXPORT_STUB(void);
	sgetopt_lib__sgetopt__DLL_AUTO_EXPORT_STUB();
	}
}
