#### template file for use with pattern-container1.mks, [GnumakeUniproc v1.0]
# ! Be sure to replace every occurrence of <angle-brackets> to be your
# actual content, or [ at least comment them out if some of them are
# not required] .

gmu_PRJ_NAME = pack-sdk-mm_snprintf


gmp_USER_POST_TARGETS += # <some make targets>
	# If you'd like something to be done after all sub-projects is built, 
	# you can your targets in this var, and executes your commands under
	# these targets.

include $(gmu_DIR_GNUMAKEUNIPROC)/pattern1cfg/compiler-env/compiler-env-all.mki
	# for gmpf_ExportCenv_sdt and gmpf_ExportCenv_vc60


include $(gmu_DIR_GNUMAKEUNIPROC)/pattern-container1.mks

